version: '3.9'

services:
  backend:
    container_name: coding_challenge_backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/data:/app/data
    restart: unless-stopped
    tty: true
    stdin_open: true

  frontend:
    container_name: coding_challenge_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5001:80"
    restart: unless-stopped
